// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6d7Y35Z7i5dFuPqz76eDUlERL5XhRsqI',
    appId: '1:599635020116:web:5451e52a4952131188e0c1',
    messagingSenderId: '599635020116',
    projectId: 'rabbit-app-flutter',
    authDomain: 'rabbit-app-flutter.firebaseapp.com',
    storageBucket: 'rabbit-app-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsE8zTkNBB055Jb3o0XmCCKN5Yu7UG_78',
    appId: '1:599635020116:android:37e97eae918dc90588e0c1',
    messagingSenderId: '599635020116',
    projectId: 'rabbit-app-flutter',
    storageBucket: 'rabbit-app-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgSeFZz-NO7AMWX8Cy_fk8djMejO1Edis',
    appId: '1:599635020116:ios:446553544835b9cd88e0c1',
    messagingSenderId: '599635020116',
    projectId: 'rabbit-app-flutter',
    storageBucket: 'rabbit-app-flutter.firebasestorage.app',
    iosBundleId: 'com.example.rabbitFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgSeFZz-NO7AMWX8Cy_fk8djMejO1Edis',
    appId: '1:599635020116:ios:446553544835b9cd88e0c1',
    messagingSenderId: '599635020116',
    projectId: 'rabbit-app-flutter',
    storageBucket: 'rabbit-app-flutter.firebasestorage.app',
    iosBundleId: 'com.example.rabbitFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6d7Y35Z7i5dFuPqz76eDUlERL5XhRsqI',
    appId: '1:599635020116:web:3f673618049c205988e0c1',
    messagingSenderId: '599635020116',
    projectId: 'rabbit-app-flutter',
    authDomain: 'rabbit-app-flutter.firebaseapp.com',
    storageBucket: 'rabbit-app-flutter.firebasestorage.app',
  );
}
